# Site settings
title: Richard Werkman
description: "Blog & Portfolio of Richard Werkman"
baseurl: "/blog"
url: "https://richardwerkman.github.io"

# Theme
theme: jekyll-theme-chirpy
avatar: assets/img/profile.png

# Author settings
author:
   name: Richard Werkman
   url: https://github.com/richardwerkman
   bio: "Developer & Blogger"

github:
   username: richardwerkman

# Social links
social:
   name: Richard Werkman
   links:
     - https://github.com/richardwerkman

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Locale
locale: en

# Date format
date_format: "%Y-%m-%d"

# Compress settings
compress_html:
  ignore:
    envs:
      - development

# Build settings
exclude:
  - "*.gemspec"
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock

# Comments
comments:
  provider: giscus

giscus:
  repo: "richardwerkman/blog"
  repo_id: "R_kgDOS4l-Dg"
  category: "Comments"
  category_id: "DIC_kwDOS4l-Ds4C_I68"
  mapping: "pathname"
  reactions_enabled: 1
  emit_metadata: 0
  lang: "en"
  input_position: "top"
  theme: "light"
